# Generated by Django 3.1.4 on 2020-12-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.URLField(max_length=256, verbose_name='Ссылка'),
        ),
    ]
