# Generated by Django 3.1.4 on 2020-12-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener', '0002_auto_20201211_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='short_link',
            field=models.CharField(default=None, max_length=256, verbose_name='Короткая ссылка'),
        ),
    ]
