# Generated by Django 3.1.4 on 2020-12-11 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener', '0006_link_short_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='short_link',
        ),
    ]
